#!/usr/bin/env bash
#
# One-way sync: mainline ../app -> this HarmonyOS (ohos) variant.
#
# Only Dart sources, assets and tests are mirrored. Everything platform- or
# shim-specific lives here and is deliberately NOT overwritten.
#
# Usage:
#   tool/sync-from-app.sh            # sync
#   tool/sync-from-app.sh --dry-run  # show what would change
#
# ---------------------------------------------------------------------------
# FILES THAT INTENTIONALLY DIFFER FROM ../app  (never overwritten by this script)
# ---------------------------------------------------------------------------
#   pubspec.yaml
#       Older Dart SDK constraint, dependency pins, ohos plugin ports, path
#       dependencies on the local shims below.
#   ohos/
#       Generated by `flutter create --platforms ohos`, plus the local debug
#       signing config (`ohos/build-profile.json5`, `ohos/signing/`).
#   README.md
#       This variant's capability report.
#   tool/sync-from-app.sh
#   tool/generate-ohos-debug-signing.sh
#   tool/generate-ohos-signing-material.js
#   shims/
#       Local stand-in packages for plugins with no HarmonyOS implementation:
#       flutter_secure_storage, share_plus, app_links, firebase_core,
#       firebase_messaging. (`image_picker` no longer needs one: the composer
#       picks photos through the native `mv2/image_picker` bridge.)
#   vendor/shadcn_ui/
#       shadcn_ui 0.56.3 with four `case TargetPlatform.ohos:` patches (the
#       ohos fork adds that enum value, which turns its exhaustive switches into
#       compile errors).
#   lib/core/storage/ohos_cache_database.dart
#       New file: SharedPreferences-backed fallback for the Drift store.
#   lib/core/data/v2ex_providers.dart
#       Adds the sqlite-native-asset probe + fallback selection.
#   lib/core/push/push_providers.dart
#       Picks HmsPushGateway on ohos instead of FirebasePushGateway.
#   lib/core/push/hms_push_gateway.dart
#       New file: HarmonyOS Push Kit implementation of Mv2PushGateway.
#   test/hms_push_gateway_test.dart
#       New file: unit tests for the HMS gateway (fake platform channels).
#   lib/features/composer/application/image_picker_providers.dart
#       Picks OhosImagePicker on ohos instead of the `image_picker`-backed
#       default. The shared gateway interface (image_picker_gateway.dart) and
#       the composer page are synced; only this provider file differs, matching
#       the push_providers.dart split.
#   lib/features/composer/application/ohos_image_picker.dart
#       New file: HarmonyOS implementation of Mv2ImagePicker over the
#       `mv2/image_picker` platform channel (photoAccessHelper).
#
# ---------------------------------------------------------------------------
# RECONCILED WITH MAINLINE (no longer excluded here):
#   lib/features/composer/presentation/composer_image_button.dart
#       Used to be excluded because the ohos build hid the button while
#       `image_picker` had no HarmonyOS port. The page now depends on the
#       Mv2ImagePicker interface / imagePickerProvider, so it is platform
#       agnostic and synced verbatim; only the provider is forked.
#   lib/core/data/v2ex_api.dart
#   lib/features/topic/application/topic_providers.dart
#   lib/features/topic/presentation/topic_detail_page.dart
#   lib/features/settings/application/settings_controller.dart
#   test/restricted_topic_test.dart
#       These used to be listed above because the restricted-topic redirect
#       classification, the `retry:` policy, the 去登录 state and the guarded
#       `SharedPreferences` hydration were fixed only in this variant. They are
#       now mirrored into ../app/, so they are synced from it like every other
#       file and must not be excluded. The shared
#       `lib/core/errors/provider_retry.dart` (`mv2Retry`) helper — used by the
#       topic / feed / node / search / notifications / member / my-list
#       providers — is synced the same way.
# ---------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_DIR="$(cd "$DEST_DIR/.." && pwd)/app"

if [[ ! -d "$SRC_DIR/lib" ]]; then
  echo "error: mainline app not found at $SRC_DIR" >&2
  exit 1
fi

RSYNC_ARGS=(-a --delete --itemize-changes)
if [[ "${1:-}" == "--dry-run" ]]; then
  RSYNC_ARGS+=(--dry-run)
elif [[ $# -gt 0 ]]; then
  echo "usage: $0 [--dry-run]" >&2
  exit 2
fi

# Paths are relative to each mirror root (lib/, assets/, test/).
EXCLUDES=(
  --exclude '/core/storage/ohos_cache_database.dart'
  --exclude '/core/data/v2ex_providers.dart'
  --exclude '/features/composer/application/image_picker_providers.dart'
  --exclude '/features/composer/application/ohos_image_picker.dart'
  --exclude '/core/push/push_providers.dart'
  --exclude '/core/push/hms_push_gateway.dart'
  --exclude '/hms_push_gateway_test.dart'
)

for sub in lib assets test; do
  echo "==> rsync $SRC_DIR/$sub/ -> $DEST_DIR/$sub/"
  rsync "${RSYNC_ARGS[@]}" "${EXCLUDES[@]}" "$SRC_DIR/$sub/" "$DEST_DIR/$sub/"
done

cat <<'EOF'

Done.

Next steps after a sync:
  1. PUB_HOSTED_URL=https://pub.dev <ohos-flutter>/bin/flutter pub get
  2. <ohos-flutter>/bin/flutter analyze
  3. <ohos-flutter>/bin/flutter build hap --debug

If ../app added a new native plugin, check whether an `*_ohos` federated
implementation exists on pub.dev; otherwise add a shim under shims/ and wire it
in pubspec.yaml (see README.md).
EOF
